#!/usr/bin/env bash
# Render PalWorldSettings.ini and Engine.ini from the environment with
# envsubst over the templates. Every OptionSettings entry has an environment
# variable with a default equal to the game's own.
# shellcheck shell=bash

# Settings whose value the ini expects in double quotes.
QUOTED_SETTINGS=(RANDOMIZER_SEED SERVER_NAME SERVER_DESCRIPTION ADMIN_PASSWORD GAME_PASSWORD ADVERTISED_IP REGION BAN_LIST_URL)

# name=default for every OptionSettings entry, in template order.
SETTINGS_DEFAULTS=(
    DIFFICULTY=None RANDOMIZER_TYPE=None RANDOMIZER_SEED= IS_RANDOMIZER_PAL_LEVEL_RANDOM=False
    DAYTIME_SPEEDRATE=1.000000 NIGHTTIME_SPEEDRATE=1.000000 EXP_RATE=1.000000 PAL_CAPTURE_RATE=1.000000
    PAL_SPAWN_NUM_RATE=1.000000 PAL_DAMAGE_RATE_ATTACK=1.000000 PAL_DAMAGE_RATE_DEFENSE=1.000000
    PLAYER_DAMAGE_RATE_ATTACK=1.000000 PLAYER_DAMAGE_RATE_DEFENSE=1.000000 PLAYER_STOMACH_DECREASE_RATE=1.000000
    PLAYER_STAMINA_DECREASE_RATE=1.000000 PLAYER_AUTO_HP_REGEN_RATE=1.000000 PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP=1.000000
    PAL_STOMACH_DECREASE_RATE=1.000000 PAL_STAMINA_DECREASE_RATE=1.000000 PAL_AUTO_HP_REGEN_RATE=1.000000
    PAL_AUTO_HP_REGEN_RATE_IN_SLEEP=1.000000 BUILD_OBJECT_HP_RATE=1.000000 BUILD_OBJECT_DAMAGE_RATE=1.000000
    BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1.000000 COLLECTION_DROP_RATE=1.000000 COLLECTION_OBJECT_HP_RATE=1.000000
    COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000 ENEMY_DROP_ITEM_RATE=1.000000 DEATH_PENALTY=Item
    ENABLE_PLAYER_TO_PLAYER_DAMAGE=False ENABLE_FRIENDLY_FIRE=False ENABLE_INVADER_ENEMY=True ACTIVE_UNKO=False
    ENABLE_AIM_ASSIST_PAD=True ENABLE_AIM_ASSIST_KEYBOARD=False DROP_ITEM_MAX_NUM=3000 DROP_ITEM_MAX_NUM_UNKO=100
    BASE_CAMP_MAX_NUM=128 BASE_CAMP_WORKER_MAX_NUM=15 DROP_ITEM_ALIVE_MAX_HOURS=1.000000
    AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=False AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.000000
    GUILD_PLAYER_MAX_NUM=20 BASE_CAMP_MAX_NUM_IN_GUILD=4 PAL_EGG_DEFAULT_HATCHING_TIME=1.000000 WORK_SPEED_RATE=1.000000
    AUTO_SAVE_SPAN=30.000000 IS_MULTIPLAY=False IS_PVP=False HARDCORE=False CHARACTER_RECREATE_IN_HARDCORE=False
    PAL_LOST=False CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=False ENABLE_NON_LOGIN_PENALTY=True ENABLE_FAST_TRAVEL=True
    IS_START_LOCATION_SELECT_BY_MAP=False EXIST_PLAYER_AFTER_LOGOUT=False ENABLE_DEFENSE_OTHER_GUILD_PLAYER=False
    INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX=False BUILD_AREA_LIMIT=False ITEM_WEIGHT_RATE=1.000000
    COOP_PLAYER_MAX_NUM=4 MAX_PLAYERS=32 "SERVER_NAME=Palworld" SERVER_DESCRIPTION=
    ADMIN_PASSWORD= GAME_PASSWORD= ADVERTISED_PORT=8211 ADVERTISED_IP= RCON_ENABLED=False RCON_PORT=25575 REGION=
    USEAUTH=True BAN_LIST_URL=https://b.palworldgame.com/api/banlist.txt REST_API_ENABLED=False REST_API_PORT=8212
    SHOW_PLAYER_LIST=False CHAT_POST_LIMIT_PER_MINUTE=30 "CROSSPLAY_PLATFORMS=(Steam,Xbox,PS5,Mac)"
    USE_BACKUP_SAVE_DATA=True SUPPLY_DROP_SPAN=180 ENABLE_PREDATOR_BOSS_PAL=True MAX_BUILDING_LIMIT_NUM=0
    SERVER_REPLICATE_PAWN_CULL_DISTANCE=15000.000000 ALLOW_GLOBAL_PALBOX_EXPORT=True ALLOW_GLOBAL_PALBOX_IMPORT=False
    EQUIPMENT_DURABILITY_DAMAGE_RATE=1.000000 ITEM_CONTAINER_FORCE_MARK_DIRTY_INTERVAL=1.000000
    ITEM_CORRUPTION_MULTIPLIER=1.000000 PHYSICS_ACTIVE_DROP_ITEM_MAX_NUM=-1 ALLOW_CLIENT_MOD=True
    PLAYER_DATA_PAL_STORAGE_UPDATE_CHECK_TICK_INTERVAL=1.000000 LOG_FORMAT_TYPE=Text IS_SHOW_JOIN_LEFT_MESSAGE=True
    MONSTER_FARM_ACTION_SPEED_RATE=1.000000 DENY_TECHNOLOGY_LIST= GUILD_REJOIN_COOLDOWN_MINUTES=0
    AUTO_TRANSFER_MASTER_CHECK_INTERVAL_SECONDS=3600.000000 AUTO_TRANSFER_MASTER_THRESHOLD_DAYS=14 MAX_GUILDS_PER_FRAME=10
    BLOCK_RESPAWN_TIME=5.000000 RESPAWN_PENALTY_DURATION_THRESHOLD=0.000000 RESPAWN_PENALTY_TIME_SCALE=2.000000
    DISPLAY_PVP_ITEM_NUM_ON_WORLD_MAP_BASE_CAMP=False DISPLAY_PVP_ITEM_NUM_ON_WORLD_MAP_PLAYER=False
    ADDITIONAL_DROP_ITEM_WHEN_PLAYER_KILLING_IN_PVP_MODE=PlayerDropItem
    ADDITIONAL_DROP_ITEM_NUM_WHEN_PLAYER_KILLING_IN_PVP_MODE=1 ADDITIONAL_DROP_ITEM_WHEN_PLAYER_KILLING_IN_PVP_MODE_ENABLED=False
    ENABLE_VOICE_CHAT=False VOICE_CHAT_MAX_VOLUME_DISTANCE=3000.000000 VOICE_CHAT_ZERO_VOLUME_DISTANCE=15000.000000
    ALLOW_ENHANCE_STAT_HEALTH=True ALLOW_ENHANCE_STAT_ATTACK=True ALLOW_ENHANCE_STAT_STAMINA=True
    ALLOW_ENHANCE_STAT_WEIGHT=True ALLOW_ENHANCE_STAT_WORK_SPEED=True ENABLE_BUILDING_PLAYER_UID_DISPLAY=False
    BUILDING_NAME_DISPLAY_CACHE_TTL_SECONDS=60
)

ENGINE_DEFAULTS=(
    LAN_SERVER_MAX_TICK_RATE=120 NET_SERVER_MAX_TICK_RATE=120 CONFIGURED_INTERNET_SPEED=104857600
    CONFIGURED_LAN_SPEED=104857600 MAX_CLIENT_RATE=104857600 MAX_INTERNET_CLIENT_RATE=104857600
    SMOOTH_FRAME_RATE=true SMOOTH_FRAME_RATE_UPPER_LIMIT=120.000000 SMOOTH_FRAME_RATE_LOWER_LIMIT=30.000000
    USE_FIXED_FRAME_RATE=false FIXED_FRAME_RATE=120 MIN_DESIRED_FRAME_RATE=60 NET_CLIENT_TICKS_PER_SECOND=120
)

# Export every name from a name=default list, keeping any value already set,
# and leave the envsubst variable list ("${A} ${B} ...") in ENVSUBST_LIST
# so substitution is restricted to exactly these names. Must be called in the
# current shell, never in $(...): the exports are the point.
ENVSUBST_LIST=""
_pal_export_defaults() {
    local entry name default
    ENVSUBST_LIST=""
    for entry in "$@"; do
        name=${entry%%=*}
        default=${entry#*=}
        [[ -n "${!name+x}" ]] || printf -v "$name" '%s' "$default"
        export "${name?}"
        ENVSUBST_LIST+="\${${name}} "
    done
}

# pal_render_settings <template> <destination>
pal_render_settings() {
    local template=$1 dest=$2
    (
        local name
        _pal_export_defaults "${SETTINGS_DEFAULTS[@]}"
        for name in "${QUOTED_SETTINGS[@]}"; do
            printf -v "$name" '"%s"' "${!name}"
            export "${name?}"
        done
        {
            printf '[/Script/Pal.PalGameWorldSettings]\n'
            envsubst "$ENVSUBST_LIST" < "$template" | tr -d '\n\r'
            printf '\n'
        } > "${dest}.tmp"
    ) && mv "${dest}.tmp" "$dest"
}

# pal_render_engine <template> <destination>
pal_render_engine() {
    local template=$1 dest=$2
    (
        _pal_export_defaults "${ENGINE_DEFAULTS[@]}"
        envsubst "$ENVSUBST_LIST" < "$template" > "${dest}.tmp"
    ) && mv "${dest}.tmp" "$dest"
}
